#! /usr/bin/env bash

if [ "$1" = "-h" ]
then
  echo "Creates a new feature branch and upstream in origin. Git username will be prepended"
  exit 0
fi

username=$(git config --get user.handle)

git checkout -b "$username/$1"

upstream
