#! /usr/bin/env bash

if [ "$1" = "-h" ]
then
  echo "Creates an upstream to match the local branch."
  exit 0
fi

remote_repo=origin

# Get current branch.
branch=$(git branch | grep \* | cut -d ' ' -f2)

# Set upstream.
git push --set-upstream $remote_repo $branch
